### Authenticate with client_id and client_secret
POST http://localhost:8181/realms/hello-microservice/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=product-service&client_secret=0NLS8ksADbkFbSMn75CcDytdWcwIzVFt

> {%
    client.test("Access token obtained from authorization server", () => {
        client.assert(response.status === 200, "Authentication failed");
        client.assert(!!response.body.access_token, "Access token is undefined");
    });

    client.global.set('access_token', response.body.access_token);
%}

###