### Authenticate to product-service
POST {{auth.host}}/{{auth.realm_path}}/{{auth.token_path}}
Content-Type: application/x-www-form-urlencoded

client_id=product-service&grant_type={{auth.grant_type}}&client_secret={{auth.secret}}

> {%
    client.test("Access token obtained from authorization server", () => {
        client.assert(response.status === 200, "Authentication failed");
        client.assert(response.body.access_token, "Access token is undefined");
    });

    client.global.set('access_token', response.body.access_token);
%}

###