### Create a new category
POST {{api.host}}/categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Category name",
  "description": "Detailed category description"
}

### Get a list of all categories
GET {{api.host}}/categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Get a category by id
GET {{api.host}}/categories/{{api.category_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Get a category by name
GET {{api.host}}/categories/by-name/{{api.category_name}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Get all products of a category
GET {{api.host}}/categories/{{api.category_id}}/products
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Update a category
PUT {{api.host}}/categories/{{api.category_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Updated category name",
  "description": "Updated detailed category description"
}

### Delete a category
DELETE {{api.host}}/categories/{{api.category_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###