### Create a new product image
POST {{api.host}}/product-images
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "url": "<paste-image-url-here>",
  "is_default": true,
  "product": {
      "id": "{{api.product_service..product_id}}"
  }
}

### Get a list of all product images
GET {{api.host}}/product-images
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Get a product image by id
GET {{api.host}}/product-images/{{api.image_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

### Update a product image
PUT {{api.host}}/product-images/{{api.image_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "url": "<paste-another-image-url-here>",
  "product": {
      "id": "{{api.product_service.product_id}}"
  },
  "is_default": true
}

### Delete a product image
DELETE {{api.host}}/product-images/{{api.image_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###