### Authenticate with username and password
POST http://localhost:8181/realms/hello-microservice/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=order-service&username=danny&password=danny.1

> {%
    client.test("Access token obtained from authorization server", () => {
        client.assert(response.status === 200, "Authentication failed");
        client.assert(!!response.body.access_token, "Access token is undefined");
    });

    client.global.set('user_access_token', response.body.access_token);
%}

### Authenticate with client_id and client_secret
POST http://localhost:8181/realms/hello-microservice/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=customer-service&client_secret=hu4rvwyZC2CKWKjuS4QE9rH2n0jcAQaw

> {%
    client.test("Access token obtained from authorization server", () => {
        client.assert(response.status === 200, "Authentication failed");
        client.assert(!!response.body.access_token, "Access token is undefined");
    });

    client.global.set('client_access_token', response.body.access_token);
%}

###