### Create a new customer
POST {{api.host}}/customers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

{
  "name": "John Doe",
  "email": "john.doe@somecompany.com",
  "phone_number": "+1 (234) 567-8900",
  "address": "123 Joyful Street",
  "city": "Ottawa",
  "state": "ON",
  "postal_code": "A1B 2C3",
  "active": true,
  "payment_methods": [
    {
      "type": "PAYPAL",
      "number": "john.doe@somecompany.com"
    }
  ]
}

### Get a list of all customers
GET {{api.host}}/customers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

### Get a list of customers by name part
GET {{api.host}}/customers/by-name-part/{{api.customer_service.customer_name_frag}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

### Get a customer by id
GET {{api.host}}/customers/{{api.customer_service.customer_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

### Get a customer by name
GET {{api.host}}/customers/by-name/{{api.customer_service.customer_name}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

### Get a customer by email
GET {{api.host}}/customers/by-email/{{api.customer_service.customer_email}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

### Get a customer by phone number
GET {{api.host}}/customers/by-phone-number/{{api.customer_service.customer_phone}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

### Update a customer
PUT {{api.host}}/customers/{{api.customer_service.customer_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

{
  "name": "Jon Dave",
  "email": "jon.dave@othercompany.org",
  "phone_number": "+1 (234) 567-8900",
  "address": "987 Avenue-du-bonheur",
  "city": "Montreal",
  "state": "QC",
  "postal_code": "Z9Y 8X7",
  "active": true,
  "payment_methods": [
    {
      "id": "<put-payment-method-id-here>",
      "type": "PAYPAL",
      "number": "jon.dave@othercompany.org"
    }
  ]
}

### Patch a customer
PATCH {{api.host}}/customers/{{api.customer_service.customer_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

{
  "name": "Jonathan Davids",
  "email": "jon.davids@othercompany.org",
  "payment_methods": [
    {
      "op": "UPDATE",
      "id": "<put-payment-method-id-here>",
      "payload": {
        "number": "jon.davids@othercompany.org"
      }
    }
  ]
}

### Delete a customer
DELETE {{api.host}}/customers/{{api.customer_service.customer_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{customer_service_access_token}}

###