### Create a new order
POST http://localhost:8080/orders
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{user_access_token}}

{
  "delivery_date": "2025-04-01T11:00",
  "customer": "67d66b4efa38ba6ba572dac6",
  "items": [
    {
      "product": "2e93e208-26f0-46bd-a78d-1595a9c1a3b4",
      "quantity": 1,
      "unit_price": 2000,
      "discount": 0.1
    },
    {
      "product": "779d1295-f968-442e-86e7-e3087c89e1ed",
      "quantity": 1,
      "unit_price": 1500,
      "discount": 0.1
    }
  ]
}

### Get a list of all orders
GET http://localhost:8080/orders
Content-Type: application/json
Accept: application/json

### Get an order by id
GET http://localhost:8080/orders/d20b90f1-874b-47fe-bca3-edb41040e36d
Content-Type: application/json
Accept: application/json

### Get an order by customer
GET http://localhost:8080/orders/by-customer/67d354e09c577d16ffd556e0
Content-Type: application/json
Accept: application/json

### Update an order
PUT http://localhost:8080/orders/c71f225f-e71b-4575-8369-4c0d45390899
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{user_access_token}}

{
  "customer": {
    "id": "67e5f82aef6fdc192f720dc3"
  },
  "items": [
    {
      "id": "9593f62e-fb48-4a45-aad7-f03be1d3e75f",
      "product": {
        "id": "3370d3b1-51c3-4f43-a635-6540770ac737"
      },
      "quantity": 1,
      "discount": 0.0,
      "unit_price": 1500
    },
    {
      "id": "18b45174-89ca-42b1-9a26-59d9a95f75cf",
      "product": {
        "id": "cf4f81ca-7b81-4fa7-a0f7-2c42d006eac7"
      },
      "quantity": 2,
      "discount": 0.0,
      "unit_price": 1300
    },
    {
      "product": {
        "id": "6041a1b0-4f11-41e5-8a35-aba4f8bb460c"
      },
      "quantity": 1,
      "discount": 0.7,
      "unit_price": 1700
    },
    {
      "product": {
        "id": "c2bcb68d-a33d-4c11-a1de-f0f9f3fe5a7c"
      },
      "quantity": 6,
      "discount": 0.2,
      "unit_price": 400
    }
  ],
  "delivery_date": "2025-03-29T18:00:00",
  "payment_method": {
    "id": "bd8511ac-797b-42f6-9166-3549783a224e"
  }
}

### Patch an order
PATCH http://localhost:8080/orders/d20b90f1-874b-47fe-bca3-edb41040e36d
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{user_access_token}}

{
  "payment_method_id": "cd084869-b63a-4abc-bb5b-f08d046f6130",
  "items": [
    {
      "op": "UPDATE",
      "id": "b5db78ae-7195-42fe-85cf-950680c5563a",
      "payload": {
        "quantity": 5
      }
    }
  ]
}

### Delete an order
DELETE http://localhost:8080/orders/1205339f-3f82-4b42-bc63-f2fbde60cd41
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{user_access_token}}

###