### Create a new product
POST {{api.host}}/products
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

{
  "name": "Product name",
  "unit_price": 5,
  "categories": [
    {
      "id": "{{api.product_service.category_id}}"
    }
  ]
}

### Get a list of all products
GET {{api.host}}/products
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

### Get a product by id
GET {{api.host}}/products/{{api.product_service.product_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

### Get a product by name
GET {{api.host}}/products/by-name/{{api.product_service.product_name}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

### Get all images of a product
GET {{api.host}}/products/{{api.product_service.product_id}}/images
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

### Get the default image of a product
GET {{api.host}}/products/{{api.product_service.product_id}}/images/default
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

### Update a product
PUT {{api.host}}/products/{{api.product_service.product_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

{
  "name": "Updated product name",
  "unit_price": 10,
  "categories": [
    {
      "id": "{{api.product_service.category_id}}"
    }
  ]
}

### Delete a product
DELETE {{api.host}}/products/{{api.product_service.product_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{product_service_access_token}}

###