POST {{auth.host}}/{{auth.realm_path}}/{{auth.token_path}}
Content-Type: application/x-www-form-urlencoded

client_id=order-service&grant_type={{auth.grant_type}}&username={{auth.username}}&password={{auth.password}}&scope={{auth.scopes}}

> {%
    client.test("Access token obtained from authorization server", () => {
        client.assert(response.status === 200, "Authentication failed");
        client.assert(!!response.body.access_token, "Access token is undefined");
    });

    client.global.set('access_token', response.body.access_token);
%}

### Get current user details
GET {{api.host}}/users/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###