### Create a new order
POST http://localhost:8083/orders
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "delivery_date": "2025-03-24T18:30",
  "customer": {
    "id": "67d354e09c577d16ffd556e0"
  },
  "payment_method": {
    "id": "b3e582fc-5463-4297-a046-83caec835af3"
  },
  "items": [
    {
      "product": {
        "id": "2d87bdf1-781f-42ae-a9a1-38d1b23bbb3f"
      },
      "quantity": 1,
      "unit_price": 1200,
      "discount": 0
    },
    {
      "product": {
        "id": "cf4f81ca-7b81-4fa7-a0f7-2c42d006eac7"
      },
      "quantity": 1,
      "unit_price": 1000,
      "discount": 0
    }
  ]
}

### Get a list of all orders
GET http://localhost:8083/orders
Content-Type: application/json
Accept: application/json

### Get a order by id
GET http://localhost:8083/orders/0bd95565-813a-4384-a0c4-af97151c55ec
Content-Type: application/json
Accept: application/json

### Get a order by customer
GET http://localhost:8083/orders/by-customer/67d354e09c577d16ffd556e0
Content-Type: application/json
Accept: application/json

### Update a order
PUT http://localhost:8083/orders/0bd95565-813a-4384-a0c4-af97151c55ec
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "delivery_date": "2025-03-17T12:00",
  "customer": {
    "id": "67d354e09c577d16ffd556e0"
  },
  "payment_method": {
    "id": "b3e582fc-5463-4297-a046-83caec835af3"
  },
  "items": [
    {
      "product": {
        "id": "6c0039fa-94bc-4cb3-9426-7f2382806d56"
      },
      "quantity": 3,
      "unit_price": 300,
      "discount": 0
    },
    {
      "product": {
        "id": "2d87bdf1-781f-42ae-a9a1-38d1b23bbb3f"
      },
      "quantity": 1,
      "unit_price": 1200,
      "discount": 0
    },
    {
      "product": {
        "id": "3370d3b1-51c3-4f43-a635-6540770ac737"
      },
      "quantity": 1,
      "unit_price": 1200,
      "discount": 0
    },
    {
      "product": {
        "id": "cf4f81ca-7b81-4fa7-a0f7-2c42d006eac7"
      },
      "quantity": 1,
      "unit_price": 1000,
      "discount": 0
    }
  ]
}

### Delete a order
DELETE http://localhost:8083/orders/0bd95565-813a-4384-a0c4-af97151c55ec
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###