### Create a new order
POST {{api.host}}/orders
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "delivery_date": "<YYYY-MM-DDThh:mm>",
  "customer": "{{api.customer_id}}",
  "items": [
    {
      "product": "{{api.product_ids[0]}}",
      "quantity": 2,
      "unit_price": 10,
      "discount": 0.05
    },
    {
      "product": "{{api.product_ids[1]}}",
      "quantity": 1,
      "unit_price": 15,
      "discount": 0.05
    }
  ]
}

### Get a list of all orders
GET {{api.host}}/orders
Content-Type: application/json
Accept: application/json

### Get an order by id
GET {{api.host}}/orders/{{api.order_id}}
Content-Type: application/json
Accept: application/json

### Get an order by customer
GET {{api.host}}/orders/by-customer/{{api.customer_id}}
Content-Type: application/json
Accept: application/json

### Update an order
PUT {{api.host}}/orders/{{api.order_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "delivery_date": "<YYYY-MM-DDThh:mm>",
  "customer": "{{api.customer_id}}",
  "items": [
    {
      "id": "<paste-generated-item-id-here>",
      "product": "{{api.product_ids[0]}}",
      "quantity": 2,
      "unit_price": 10,
      "discount": 0.05
    },
    {
      "id": "<paste-generated-item-id-here>",
      "product": "{{api.product_ids[1]}}",
      "quantity": 2,
      "unit_price": 15,
      "discount": 0.05
    }
  ]
}

### Patch an order
PATCH {{api.host}}/orders/{{api.order_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "items": [
    {
      "op": "ADD",
      "payload": {
        "product_id": "{{api.product_ids[2]}}",
        "unit_price": 5,
        "discount": 0.05,
        "quantity": 2
      }
    },
    {
      "op": "UPDATE",
      "payload": {
        "product_id": "{{api.product_ids[0]}}",
        "unit_price": 10,
        "discount": 0.05,
        "quantity": 1
      }
    },
    {
      "op": "REMOVE",
      "payload": {
        "product_id": "{{api.product_ids[1]}}"
      }
    }
  ]
}

### Delete an order
DELETE {{api.host}}/orders/{{api.order_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

###