services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-server
    restart: unless-stopped
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_CFG_BROKER_ID: 0
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-server:9093
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - ./volumes/kafka:/bitnami/kafka
    networks:
      - default

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 9090:8080
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-server:9092
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
    networks:
      - default